// Generated by scripts/refresh-test-stats.mjs — do not hand-edit.
// Run `pnpm stats:refresh` to regenerate after spec changes.
export const TEST_STATS = {
  unit: 160,
  unitFiles: 16,
  e2e: 168,
  e2eFiles: 10,
  e2eNaive: 686,
  projects: 7,
  engines: 3,
} as const;

export type TestStats = typeof TEST_STATS;
