// Generated by scripts/refresh-test-stats.mjs — do not hand-edit.
// Run `pnpm stats:refresh` to regenerate after spec changes.
export const TEST_STATS = {
  unit: 260,
  unitFiles: 21,
  e2e: 223,
  e2eFiles: 12,
  e2eNaive: 854,
  projects: 7,
  engines: 3,
} as const;

export type TestStats = typeof TEST_STATS;
